CREATE VIEW ESTOQUE_PRECO AS
SELECT P.CODIGO
      ,Sum(E.QTDE_ESTOQUE_ATUAL) AS ESTOQUE
         ,CASE WHEN PROMO.Preco IS NULL THEN PR.PRECO ELSE PROMO.Preco END AS PRECO
FROM PROD_SERV AS P
INNER JOIN ESTOQUE_ATUAL AS E ON(P.ORDEM=E.ORDEM_PROD_SERV)
INNER JOIN PROD_SERV_PRECOS AS PR ON(P.ORDEM=PR.ORDEM_PROD_SERV)
LEFT JOIN (SELECT P.CODIGO,sum(E.QTDE_ESTOQUE_ATUAL) AS ESTOQUE,PR.PRECO, P.Ordem 
              FROM PROD_SERV AS P
              INNER JOIN ESTOQUE_ATUAL AS E ON(P.ORDEM=E.ORDEM_PROD_SERV)
              INNER JOIN PROD_SERV_PROMOCAO AS PR ON(P.ORDEM=PR.ORDEM_PROD_SERV)
              WHERE E.Ordem_Filial IN(12,13)
              AND PR.ORDEM_TABELA_PRECO='13'
              AND GETDATE() BETWEEN pr.Data_Inicial AND pr.Data_Final
              AND GETDATE()<=pr.Data_Final
              OR CONVERT(VARCHAR,GETDATE()) BETWEEN CONVERT(VARCHAR,pr.Data_Inicial) AND CONVERT(VARCHAR,pr.Data_Final)
              AND CONVERT(VARCHAR,GETDATE())>=CONVERT(VARCHAR,Data_Final)
		      OR CONVERT(VARCHAR,GETDATE(),103) BETWEEN CONVERT(VARCHAR,pr.Data_Inicial,103) AND CONVERT(VARCHAR,pr.Data_Final,103)
              AND CONVERT(VARCHAR,GETDATE(),103)>=CONVERT(VARCHAR,Data_Final,103)
              GROUP BY P.CODIGO,PR.PRECO, P.Ordem ) PROMO ON PROMO.Ordem = P.Ordem
WHERE E.ORDEM_FILIAL IN(12,13)
AND PR.ORDEM_TABELA_PRECO='13'
GROUP BY P.CODIGO,PR.PRECO,PROMO.PRECO